healthy_food/config/routes.rb
Rails.application.routes.draw do
  resources :diseases
  resources :posts
  resources :comments
  resources :users
  resources :recipes
  resources :saved_recipes
  resources :saved_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'users#index'
  root 'welcome#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'saved', to: 'users#my_saved'
  post 'save_post', to: 'users#add_post_to_saves'
  post 'save_recipe', to: 'users#add_recipe_to_saves'

  get 'contact_us', to: 'welcome#contact_us'

  get 'search', to: 'searches#search'


end

healthy_food/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user # means that one post has one user
 # belongs_to :comment
  has_one_attached :description_image
  has_many :comments

  # the posts that the user saved
  has_many :user_posts
  has_many :users, through: :user_posts

 # database validations
  validates :user_id, presence: true
end

healthy_food/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   params[:search_param].strip!
  #   @posts = Post.where('name like ?', "%#{params[:search_param]}%")
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:description, :no_of_likes, :no_of_saved,
                                 :no_of_comments, :user_id, :description_image,:name)
  end

  def require_same_user
    # if the current user isn't the owner of this post nor an admin..
    # it can't edit or delete it
    if current_user != @post.user and !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own articles'
      redirect_to root_path
    end
  end

end

healthy_food/app/helpers/posts_helper.rb
module PostsHelper
end

healthy_food/app/views/posts/_form.html.erb
<body class="background">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field text-center">
    <%= form.file_field :description_image %>
  </div>

  <div class="form-group row">
    <div class="control-label col-sm-2">
    </div>
    <div class="col-sm-8">
      <%= form.text_field :name, class: "form-control", placeholder: "Post name", autofocus: true %>
    </div>
  </div>


  <div class="form-group row">
    <div class="control-label col-sm-2">
    </div>
    <div class="col-sm-8">
      <%= form.text_area :description, class: "form-control", placeholder: "Description ...", autofocus: true %>
    </div>
  </div>


  <div class="form-group row">
    <div class="control-label col-sm-2">
    </div>
    <div class=" actions col-sm-offset-2 col-sm-9">
      <%= form.submit "Create post", class: 'btn btn-success btn-lg' %>
      <%= link_to 'Cancel', posts_path , class: 'btn btn-warning btn-lg'%>
    </div>
  </div>
<% end %>
</body>

healthy_food/app/views/posts/_post.html.erb
<!--user posts-->
<% obj.each do |post| %>
  <div class="jumbotron">
    <div class="post">
      <div class="chip">
        <% if post.user.profile_photo.attached? %>
          <%= image_tag(post.user.profile_photo, :alt => "Person", width: "96", height: "96") %>
        <% else %>
          <%= image_tag("img_avatar.png", class: "img-responsive", width: "160", height: "160") %>
        <% end %>

        <%= link_to post.user.username, user_path(post.user) %>
      </div>

      <!--drop down list-->
      <div class=" float-right">
        <div class="btn-group">
          <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-option-horizontal"></span>
          </button>
          <% if logged_in? && (current_user == post.user || current_user.admin?) %>

            <div class="dropdown-menu">
              <%= link_to "Edit", edit_post_path(post), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Delete", post_path(post), method: :delete,
                          data: {confirm: "Are you sure you want to delete the post?"},
                          class: "dropdown-item" %>
            </div>
          <% end %>
        </div>
      </div>
      <!--end of the drop down list-->
      <hr>
      <div class="post-recipe-title">
        <%= link_to post.name, post_path(post) %>
      </div>
      <br>

      <div class="post-recipe-body">
        <%= truncate(post.description, length: 100) %>
      </div>
      <!--post image-->
      <% if post.description_image.attached? %>
        <%= image_tag(post.description_image, class: "img-responsive", width: "200", height: "200") %>
      <% end %>

      <div class="move">

        <button class="btn btn-success">Like <span class="badge LCS"><%= post.no_of_likes %></span></button>
        <button class="btn btn-success">Comment <span class="badge LCS"><%= post.no_of_comments %></span></button>

        <% if current_user.post_not_saved?(post.id) %>
          <%= link_to "Save", save_post_path(user: current_user, savedpost: post), class: "btn btn-success", method: :post %>
        <% else %>
          <button type="button" class="btn btn-success" disabled>Saved</button>
        <% end %>

      </div>
      <hr>
      <div class="post-recipe-meta-details">
        <small>Created by: <%= post.user.username if post.user %>,
          <%= time_ago_in_words(post.created_at) %> ago,
          last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
      </div>
    </div>
  </div>
<% end %>

healthy_food/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

healthy_food/app/views/posts/index.html.erb
<style>

  .container-fluid label{
    color: steelblue;
  }
  .container-fluid .move{
    text-align: right;
  }
  {
    box-sizing: border-box;
  }

  /* Style the close button */
  .close {
    position: absolute;
    right: 0;
    top: 0;
    padding: 12px 16px 12px 16px
  }
  .close:hover {
    background-color: #f44336;
    color: white;
  }
  /* Style the input */
  .modal .modal-content .modal-body .header input {
    width: 75%;
    padding: 10px;
    float: left;
    font-size: 13px;
  }

  /* Style the "Add" button */
  .addBtn {
    padding: 10px;
    width: 25%;
    background: #d9d9d9;
    color: #555;
    float: left;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
    transition: 0.3s;
  }

  .addBtn:hover {
    background-color: #bbb;
  }
  .header:after {
    content: "";
    display: table;
    clear: both;
  }


  /* Style the list items */
  .modal .modal-content .modal-body  ul li {
    cursor: pointer;
    position: relative;
    padding: 12px 8px 12px 40px;
    background: #eee;
    font-size: 18px;
    transition: 0.2s;

    /* make the list items unselectable */
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  /* Set all odd list items to a different color (zebra-stripes) */
  .modal .modal-content .modal-body  ul li:nth-child(odd) {
    background: #f9f9f9;
  }

  .modal .modal-content .modal-body ul li:hover {
    background: #ddd;
  }

  /* When clicked on, add a background color and strike out text */
  .modal .modal-content .modal-body ul li.checked {
    background: #888;
    color: #fff;
    text-decoration: line-through;
  }

  /* Add a "checked" mark when clicked on */
  .modal .modal-content .modal-body ul li.checked::before {
    content: '';
    position: absolute;
    border-color: #fff;
    border-style: solid;
    border-width: 0 2px 2px 0;
    top: 10px;
    left: 16px;
    transform: rotate(45deg);
    height: 15px;
    width: 7px;
  }
  .header {
    background-color: black;
    padding: 30px 40px;
    text-align: center;
  }

  /* Clear floats after the header */
  .header:after {
    content: "";
    display: table;
    clear: both;
  }
  .modal .modal-content .modal-body .header h2{
    color: white;

  }
  /**/
  body {
    font-family: "Lato", sans-serif;
    transition: background-color .5s;
  }

  #main {
    transition: margin-left .5s;
    padding: 16px;
  }

  /**/
  /* Three columns side by side */
  .column {
    float: left;
    width: 33.3%;
    margin-bottom: 16px;
    padding: 0 8px;
  }

  /* Display the columns below each other instead of side by side on small screens */
  @media (max-width: 650px) {
    .column {
      width: 100%;
      display: block;
    }
  }
  /**/
  /* Add some shadows to create a card effect */
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  }

  /* Some left and right padding inside the container */
  .container {
    padding: 0 16px;
  }

  /* Clear floats */
  .container::after, .row::after {
    content: "";
    clear: both;
    display: table;
  }

  .title {
    color: grey;
  }

  .button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 25%;
  }

  .button:hover {
    background-color: #555;
  }

  #userpost {
    width: 100%;
    height:150px;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }




  .post {
    border: 0px solid #ddd;
    margin-bottom: 20px;
  }

  .move {
    text-align: right;
  }

  {
    box-sizing: border-box
  ;
  }
  .chip {
    display: inline-block;
    padding: 0 25px;
    height: 50px;
    font-size: 16px;
    line-height: 50px;
    border-radius: 25px;
    background-color: #f1f1f1;
  }

  .chip img {
    float: left;
    margin: 0 10px 0 -25px;
    height: 50px;
    width: 50px;
    border-radius: 50%;
  }
</style>


<body class="background">
<div class="container-fluid ">
  <div class="row">
    <div class="col-sm-3">
      <div class="jumbotron">

        <p>Specialists</p>

        <div class="chip">
          <img src="http://book.jirengu.com/jirengu-inc/jrg-renwu11/homework/LiuZheXin/task8/img/man.png" alt="Person" width="96" height="96">
          name
        </div>
        <br>
        <div class="move">
          <a href="#">chat <span class="badge"></span></a>
        </div>
        <hr>


        <div class="chip">
          <img src="http://book.jirengu.com/jirengu-inc/jrg-renwu11/homework/LiuZheXin/task8/img/man.png" alt="Person" width="96" height="96">
          name
        </div>
        <br>
        <div class="move">
          <a href="#">chat <span class="badge"></span></a>
        </div>
        <hr>


      </div>
    </div>

    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12">
          <p id="notice"><%= notice %></p>
          <%= render 'post', obj: @posts %>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>
</body>

healthy_food/app/views/posts/new.html.erb
<h1 class="text-center">New Post</h1>
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-6">
    <%= render 'form', post: @post %>
  </div>
  <div class="col-sm-3">
  </div>
</div>

healthy_food/app/views/posts/show.html.erb
<body class="background">
<div class="container-fluid ">
  <div class="row">
    <div class="col-sm-3">
    </div>

    <div class="col-sm-6 jumbotron">
      <p id="notice"><%= notice %></p>

      <div class="post">
        <div class="chip">
          <% if @post.user.profile_photo.attached? %>
            <%= image_tag(@post.user.profile_photo, :alt => "Person", width: "96", height: "96") %>
          <% else %>
            <%= image_tag("img_avatar.png", class: "img-responsive", width: "160", height: "160") %>
          <% end %>

          <%= link_to @post.user.username, user_path(@post.user) %>
        </div>

        <!--drop down list-->
        <div class=" float-right">
          <div class="btn-group">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-option-horizontal"></span>
            </button>
            <% if logged_in? && (current_user == @post.user || current_user.admin?) %>

              <div class="dropdown-menu">
                <%= link_to "Edit", edit_post_path(@post), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Delete", post_path(@post), method: :delete,
                            data: {confirm: "Are you sure you want to delete the post?"},
                            class: "dropdown-item" %>
              </div>
            <% end %>
          </div>
        </div>
        <!--end of the drop down list-->
        <hr>
        <div class="post-recipe-title">
          <%= link_to @post.name, post_path(@post) %>
        </div>


        <div class="post-recipe-body">
          <%= truncate(@post.description, length: 100) %>
        </div>
        <!--post image-->
        <% if @post.description_image.attached? %>
          <%= image_tag(@post.description_image, class: "img-responsive", width: "200", height: "200") %>
        <% end %>

        <div class="move">
          <button class="btn btn-success">Like <span class="badge LCS"><%= @post.no_of_likes %></span></button>
          <button class="btn btn-success">Comment <span class="badge LCS"><%= @post.no_of_comments %></span></button>
          <% if current_user.post_not_saved?(@post.id) %>
            <%= link_to "Save", save_post_path(user: current_user, savedpost: @post), class: "btn btn-success", method: :post %>
          <% else %>
            <button type="button" class="btn btn-success" disabled>Saved</button>
          <% end %>
        </div>
        <hr>
        <div class="post-recipe-meta-details">
          <small>Created by: <%= @post.user.username if @post.user %>,
            <%= time_ago_in_words(@post.created_at) %> ago,
            last updated: <%= time_ago_in_words(@post.updated_at) %> ago</small>
        </div>
      </div>



    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>
</body>