healthy_food/config/routes.rb
Rails.application.routes.draw do
  resources :diseases
  resources :posts
  resources :comments
  resources :users
  resources :recipes
  resources :saved_recipes
  resources :saved_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'users#index'
  root 'welcome#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'saved', to: 'users#my_saved'
  post 'save_post', to: 'users#add_post_to_saves'
  post 'save_recipe', to: 'users#add_recipe_to_saves'

  get 'contact_us', to: 'welcome#contact_us'

  get 'search', to: 'searches#search'


end

healthy_food/app/views/layouts/_footer.html.erb
<div class="footer" style="height:200px;background-color:#212F3C;font-size:15px ;width:100%">
  <br>
  <br>
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-1">
      <a href="#">English(UK)</a>
    </div>
    <div class="col-sm-1">
      <a href="#"> العربية </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Français </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Italiano </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Deutsch </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Русский </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Indonesia </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Türkçe </a>
    </div>
    <div class="col-sm-1">
      <a href="#"> Português</a>
    </div>
    <div class="col-sm-1">
      <a href="#"> EspañolBahasa </a>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-1">
      <img width="30" height="30" src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/twitter.svg">
    </div>
    <div class="col-sm-1">
      <img width="30" height="30" src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/facebook.svg">
    </div>
    <div class="col-sm-1">
      <img width="30" height="30" src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/instagram.svg">
    </div>
    <div class="col-sm-1">
      <img width="30" height="30" src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/medium.svg">
    </div>
    <div class="col-sm-4">
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-5">
    </div>
    <div class="col-sm-4">
      <a style="color: steelblue">&copy;</a><%= link_to "CSED 2020 Health Food", root_path %>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>

healthy_food/app/views/layouts/_navigation.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Healthy-Food", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if logged_in? %>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <% if current_user.is_specialist? %>
          <li class="nav-item ">
            <%= link_to "Diseases", diseases_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item ">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to ' New Post', new_post_path %>
            <div class="dropdown-divider"></div>
            <%= link_to ' New Recipe', new_recipe_path %>

            <% if current_user.is_specialist? %>
              <div class="dropdown-divider"></div>
              <%= link_to 'New Disease', new_disease_path %>
            <% end %>
          </div>
        </li>
      </ul>

      <!--Start of search-->
      <div id="lookup">
        <%= form_tag search_path, method: :get,class:"form-inline  mr-auto", id: 'lookup-form' do %>
          <div class="form-group  no-padding text-center  input-group">
              <%= text_field_tag :search_param, params[:search_param],
                                 placeholder: "Search", autofocus: true,
                                 class: "form-control search-box " %>

            <div class="input-group-append">
              <%= button_tag(type: :submit, class: "btn btn-outline-secondary") do %>
                <i class="fa fa-search"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <!--End of search-->

      <li><span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span></li>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link fa fa-sign-out" %>
        </li>
      </ul>
    </div>
    </nav>

    <!--side bar-->
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <br><br><br>
      <%= link_to "Profile", user_path(current_user) %><br>
      <%= link_to "Settings", edit_user_path(current_user) %><br>
      <%= link_to "Saved", saved_path %><br>
      <%= link_to "Contact us", contact_us_path %><br>
      <%= link_to 'Delete account', current_user, method: :delete, data: {confirm: 'Are you sure you want to delete your account?'} %>
    </div>

  <% else %>

    <li><%= link_to 'Log in', login_path, class: "" %></li>
    <li><%= link_to 'Sign up', signup_path, class: "" %></li>

  <% end %>

  <!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
  <div id="main">

  </div>

  <script>
      function openNav() {
          document.getElementById("mySidenav").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
          document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
      }

      function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
          document.getElementById("main").style.marginLeft = "0";
          document.body.style.backgroundColor = "white";
      }
  </script>

healthy_food/app/views/layouts/_show_image.html.erb
<%= image_tag(@recipe.image) %>

healthy_food/app/views/layouts/_upload_image.html.erb
<%= form_for @recipe do |recipe| %>
  <%= recipe.file_field :image %>
<% end %>

healthy_food/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>HealthyFood</title>
  <meta charset="utf-8">
  <!--phone-->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--shortcut icon-->
  <%= favicon_link_tag 'logo.png' %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<header>
  <%= render 'layouts/navigation' %> <!--if @navigation_bar-->
</header>
<%= yield %>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</body>
</html>