healthy_food/config/routes.rb
Rails.application.routes.draw do
  resources :diseases
  resources :posts
  resources :comments
  resources :users
  resources :recipes
  resources :saved_recipes
  resources :saved_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'users#index'
  root 'welcome#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'saved', to: 'users#my_saved'
  post 'save_post', to: 'users#add_post_to_saves'
  post 'save_recipe', to: 'users#add_recipe_to_saves'

  get 'contact_us', to: 'welcome#contact_us'

  get 'search', to: 'searches#search'


end

healthy_food/app/models/user.rb
class User < ApplicationRecord
  #belongs_to :recipe
  has_one_attached :profile_photo
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :user_diseases
  has_many :diseases, through: :user_diseases
  has_many :saved_recipes
  has_many :savedrecipes, through: :saved_recipes
  has_many :saved_posts
  has_many :savedposts, through: :saved_posts
  # database validations
  validates :username, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 100}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}

  VALID_WEIGHT_HEIGHT_REGEX = /[0-9]+\.?[0-9]*/i
  validates :weight, presence: true,
            format: {with: VALID_WEIGHT_HEIGHT_REGEX}

  validates :height, presence: true,
            format: {with: VALID_WEIGHT_HEIGHT_REGEX}

  validates :gender, presence: true

  validates :first_name, presence: true, length: {minimum: 3, maximum: 100}

  validates :last_name, presence: true, length: {minimum: 3, maximum: 100}

  validates :birthdate, presence: true

  has_secure_password
  # validates :password, presence: true, length: {minimum: 6, maximum: 200}


  def post_not_saved?(post_id)
    # if count is < 1 means that the count is zero so it isn't saved
    saved_posts.where(savedpost_id: post_id).count < 1
  end

  def recipe_not_saved?(recipe_id)
    # if count is < 1 means that the count is zero so it isn't saved
    saved_recipes.where(savedrecipe_id: recipe_id).count < 1
  end


end

healthy_food/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  # before_action :flag_navigation_bar, only: [:show, :edit]


  # GET /users
  # GET /users.json
  def index
    # if the user is logged in he isn't allowed to go to the welcome page
    # redirect_to profile_path if logged_in?
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  # the profile page for the user
  def show;
  end

  # GET /users/new
  # sign up form
  def new
    # if the user is logged in he isn't allowed to go back to the sign up page
    redirect_to posts_path if logged_in?

    @user = User.new
  end


  def my_saved
    @saved_posts = current_user.savedposts
    @saved_recipes = current_user.savedrecipes
  end



  def add_post_to_saves
    @post = User.find(params[:savedpost])
    current_user.saved_posts.build(savedpost_id: @post.id)
    if current_user.save
      flash[:notice] = 'Post was successfully added'
    else
      flash[:danger] = 'There was something wrong with the post saving'
    end
    # redirect to the same page
    redirect_back(fallback_location:"/")
  end

  def add_recipe_to_saves
    @recipe = User.find(params[:savedrecipe])
    current_user.saved_recipes.build(savedrecipe_id: @recipe.id)
    if current_user.save
      flash[:notice] = 'Recipe was successfully added'
    else
      flash[:danger] = 'There was something wrong with the recipe saving'
    end
    # redirect to the same page
    redirect_back(fallback_location:"/")
  end

  # GET /users/1/edit
  # edit will be handled by update function
  # so when I click the save button in the setting (edit) page the update function is called
  def edit;
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_path(@user) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      # lw l user l e7na bn3dl feh dh (user_params dii l data l mt3dla) et3mlo update fl db mn 8er errors
      if @user.update(user_params)
        # e3mlo redirect 3la l show (home)page
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else # lw 7sl error w m3rfsh y save fl db
        format.html { render :edit } # sebo zy m hwa fl edit (settings) page
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :mobile_number,
                                 :username, :password, :email, :birthdate,
                                 :is_specialist, :weight, :height,
                                 :gender, :profile_photo, disease_ids: [])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  # this will prevent the non admin users from having access to destroy action
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = 'Only admin users can perform that action'
      redirect_to root_path
    end
  end

  # def flag_navigation_bar
  #   @navigation_bar = true
  # end

end

healthy_food/app/helpers/users_helper.rb
module UsersHelper
end

healthy_food/app/views/users/_form.html.erb
<div class="container-fluid ">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
      </div>
      <div class="col-sm-7">
        <div class="jumbotron">

          <%= form_with(model: user, local: true) do |form| %>
            <% if user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                  <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.text_field :first_name, placeholder: "First name", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.text_field :last_name, placeholder: "Last name", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.telephone_field :mobile_number, placeholder: "Mobile number", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.text_field :username, placeholder: "Username", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.password_field :password, placeholder: "Password", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.email_field :email, placeholder: "Email address", class: "form-control" %>
            </div>


            <div class="field">
              <%= form.number_field :weight, placeholder: "Your weight", class: "form-control" %>
            </div>

            <div class="field">
              <%= form.number_field :height, placeholder: "Your height", class: "form-control" %>
            </div>


            <div class="form-group">
              <div class="row">
                <div class="col-sm-offset-2 col-sm-8 ">
                  <b>Diseases: </b><br>
                  <%= form.collection_check_boxes :disease_ids, Disease.all, :id, :name do |cb| %>
                    <% cb.label(class: "checkbox-inline input_checkbox ") { cb.check_box(class: "checkbox") + cb.text } %>
                  <% end %>
                </div>
              </div>
            </div>


            <div class="field">
              <b>Brithday:</b><br>
              <%= form.date_field :birthdate %>
            </div>

            <div class="control-group">
              <b class="control-label">Sign as:</b><br>
              <%= form.radio_button :is_specialist, 'true' %>Specialist
              <%= form.radio_button :is_specialist, 'false' %>Client
            </div>
            <br>
            <div class="control-group">
              <b class="control-label">Gender:</b><br>
              <div class="controls">
                <%= form.select(:gender,
                                options_for_select([['Female', 'Female'], ['Male', 'Male']])) %>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "Sign up", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

healthy_food/app/views/users/edit.html.erb
<body class="background">

<div class="container-fluid ">

  <h1>Settings</h1>
  <br>
  <hr>

  <%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="row">
      <div class="col-sm-6">
        <h4>Profile image</h4>
        <a href="#demo11" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo11" class="collapse">
          <%= form.file_field :profile_photo %>
          <br><br>
          <a href="#demo11" data-toggle="collapse">
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-sm-6">
        <h4>name</h4>
        <a href="#demo3" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo3" class="collapse">
          <label for="ex2">First:</label>
          <%= form.text_field :first_name, placeholder: "First name", class: "form-control", id: "ex2" %>
          <label for="ex2">Last:</label>
          <%= form.text_field :last_name, placeholder: "Last name", class: "form-control", id: "ex2" %>
          <br>
          <a href="#demo3" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>Mobile number</h4>
        <a href="#demo4" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo4" class="collapse">
          <label for="ex2">Mobile number:</label>
          <%= form.telephone_field :mobile_number, placeholder: "Mobile number", class: "form-control", id: "ex2" %>
          <p>Note: You should enter a valid phone number. </p>
          <br>
          <a href="#demo4" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>username</h4>
        <a href="#demo1" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo1" class="collapse">
          <p>Your public username is the same as your Timeline address:</p>
          <label for="ex2">Username:</label>
          <%= form.text_field :username, placeholder: "Username", class: "form-control", id: "ex2" %>
          <p>Note: Your username should include your authentic name. </p>
          <br>
          <a href="#demo1" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-6">
        <h4>password</h4>
        <a href="#demo2" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo2" class="collapse">
          <label for="pwd">New:</label>
          <%= form.password_field :password, placeholder: "Password", class: "form-control", id: "pwd" %>
          <br>
          <a href="#demo2" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>Email</h4>
        <a href="#demo5" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo5" class="collapse">
          <label for="ex2">Email:</label>
          <%= form.email_field :email, placeholder: "Email address", class: "form-control", id: "ex2" %>
          <p>Note: You should include a valid email address. </p>
          <br>
          <a href="#demo5" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-sm-5">
        <h4>Weight</h4>
        <a href="#demo6" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo6" class="collapse">
          <label for="ex2">Weight:</label>
          <%= form.number_field :weight, placeholder: "Your weight", class: "form-control", id: "ex2" %>

          <p>Note: Enter your current weight so we will be able to offer the best suitable meals for you. </p>
          <br>
          <a href="#demo6" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-sm-5">
        <h4>Height</h4>
        <a href="#demo7" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo7" class="collapse">
          <label for="ex2">Height:</label>
          <%= form.number_field :height, placeholder: "Your height", class: "form-control", id: "ex2" %>
          <p>Note: Enter your current height so we will be able to offer the best suitable meals for you. </p>
          <br>
          <a href="#demo7" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>Diseases</h4>
        <a href="#demo8" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo8" class="collapse">
          <label for="ex2">Diseases:</label>
          <%= form.collection_check_boxes :disease_ids, Disease.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox ") { cb.check_box(class: "checkbox") + cb.text } %>
          <% end %>
          <p>Note: Enter your current diseases so we will be able to offer the best suitable meals for you. </p>
          <br>
          <a href="#demo8" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>Birthday</h4>
        <a href="#demo9" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo9" class="collapse">
          <label for="ex2">Birthday:</label>
          <%= form.date_field :birthdate %>
          <p>Note: Enter your correct birth date so we will be able to offer the best suitable meals for you. </p>
          <br>
          <a href="#demo9" data-toggle="collapse">
            <button type="button" class="btn btn-info">Save changes</button>
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>


    <div class="row">
      <div class="col-sm-5">
        <h4>Gender</h4>
        <a href="#demo10" data-toggle="collapse">
          <button type="button" class="btn btn-link">Edit</button>
        </a>
        <div id="demo10" class="collapse">
          <label for="ex2">Gender:</label>

          <div class="control-group">
            <div class="controls">
              <%= form.select(:gender,
                              options_for_select([['Female', 'Female'], ['Male', 'Male']])) %>
            </div>
          </div>
          <br>
          <a href="#demo10" data-toggle="collapse">
            <button type="button" class="btn btn-info">Cancel</button>
          </a>
        </div>
      </div>
    </div>
    <hr>

    <br>
    <br>
    <div class="actions">
      <%= form.submit "Save changes", class: "btn btn-success " %>
    </div>
  <% end %>
</div>

</body>

healthy_food/app/views/users/home.html.erb
<style>

  .container-fluid label {
    color: steelblue;
  }

  .container-fluid .move {
    text-align: right;
  }

  {
    box-sizing: border-box;
  }


  /* Style the input */
  .modal .modal-content .modal-body .header input {
    width: 75%;
    padding: 10px;
    float: left;
    font-size: 13px;
  }

  /* Style the "Add" button */
  .addBtn {
    padding: 10px;
    width: 25%;
    background: #d9d9d9;
    color: #555;
    float: left;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
    transition: 0.3s;
  }

  .addBtn:hover {
    background-color: #bbb;
  }

  .header:after {
    content: "";
    display: table;
    clear: both;
  }


  /* Style the list items */
  .modal .modal-content .modal-body ul li {
    cursor: pointer;
    position: relative;
    padding: 12px 8px 12px 40px;
    background: #eee;
    font-size: 18px;
    transition: 0.2s;

    /* make the list items unselectable */
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  /* Set all odd list items to a different color (zebra-stripes) */
  .modal .modal-content .modal-body ul li:nth-child(odd) {
    background: #f9f9f9;
  }

  .modal .modal-content .modal-body ul li:hover {
    background: #ddd;
  }

  /* When clicked on, add a background color and strike out text */
  .modal .modal-content .modal-body ul li.checked {
    background: #888;
    color: #fff;
    text-decoration: line-through;
  }

  /* Add a "checked" mark when clicked on */
  .modal .modal-content .modal-body ul li.checked::before {
    content: '';
    position: absolute;
    border-color: #fff;
    border-style: solid;
    border-width: 0 2px 2px 0;
    top: 10px;
    left: 16px;
    transform: rotate(45deg);
    height: 15px;
    width: 7px;
  }

  .header {
    background-color: black;
    padding: 30px 40px;
    text-align: center;
  }

  /* Clear floats after the header */
  .header:after {
    content: "";
    display: table;
    clear: both;
  }

  .modal .modal-content .modal-body .header h2 {
    color: white;

  }

  #main {
    transition: margin-left .5s;
    padding: 16px;
  }



  /**/
  /* Three columns side by side */
  .column {
    float: left;
    width: 33.3%;
    margin-bottom: 16px;
    padding: 0 8px;
  }

  /* Display the columns below each other instead of side by side on small screens */
  @media (max-width: 650px) {
    .column {
      width: 100%;
      display: block;
    }
  }

  /**/
  /* Add some shadows to create a card effect */
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  }

  /* Some left and right padding inside the container */
  .container {
    padding: 0 16px;
  }

  /* Clear floats */
  .container::after, .row::after {
    content: "";
    clear: both;
    display: table;
  }

  .title {
    color: grey;
  }

  .button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 25%;
  }

  .button:hover {
    background-color: #555;
  }


  /**/
  .chip {
    display: inline-block;
    padding: 0 25px;
    height: 50px;
    font-size: 16px;
    line-height: 50px;
    border-radius: 25px;
    background-color: #f1f1f1;
  }

  .chip img {
    float: left;
    margin: 0 10px 0 -25px;
    height: 50px;
    width: 50px;
    border-radius: 50%;
  }

  /**/

  #userpost {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }

</style>
<body class="background">

<div class="container-fluid ">

  <div class="row ">
    <div class="col-sm-3">
      <div class="jumbotron">
        <p>Specialists</p>
        <div class="chip">
          <img src="http://book.jirengu.com/jirengu-inc/jrg-renwu11/homework/LiuZheXin/task8/img/man.png" alt="Person" width="96" height="96">
          name
        </div>
        <br>
        <div class="move">
          <a href="#">add <span class="badge"></span></a>
        </div>
        <hr>
        <div class="chip">
          <img src="http://book.jirengu.com/jirengu-inc/jrg-renwu11/homework/LiuZheXin/task8/img/man.png" alt="Person" width="96" height="96">
          name
        </div>
        <br>
        <div class="move">
          <a href="#">add <span class="badge"></span></a>
        </div>
        <hr>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12">
          <div class="jumbotron">
            <form>
              <textarea id="userpost" rows="4" cols="50" name="comment" placeholder="What's in your mind ?">
</textarea>
              <input type="submit" value="Post">
            </form>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="jumbotron">
            <br>
            <div class="chip">
              <img src="http://book.jirengu.com/jirengu-inc/jrg-renwu11/homework/LiuZheXin/task8/img/man.png" alt="Person" width="96" height="96">
              name
            </div>
            <br><br>
            <p>write some thing here...........</p>
            <hr>

            <div class="move">
              <button class="btn btn-success">Like <span class="badge LCS" >5</span></button>
              <button class="btn btn-success">Comment <span class="badge LCS">2</span></button>
              <button class="btn btn-success">Save <span class="badge LCS">1</span></button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="jumbotron">

        <p>Recipes</p>
        <div class="chip">
          <%=image_tag("breakfast.jpg",width: '96',height: '96',:alt => 'Food') %>
          food
        </div>
        <br>
        <div class="move">
          <a href="#">save <span class="badge"></span></a>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

healthy_food/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Mobile number</th>
    <th>Username</th>
    <th>Password</th>
    <th>Email</th>
    <th>Brithdate</th>
    <th>Is specialist</th>
    <th>Weight</th>
    <th>Height</th>
    <th>Diseases</th>
    <th>Gender</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.mobile_number %></td>
      <td><%= user.username %></td>
      <td><%= user.password %></td>
      <td><%= user.email %></td>
      <td><%= user.birthdate %></td>
      <td><%= user.is_specialist %></td>
      <td><%= user.weight %></td>
      <td><%= user.height %></td>
      <td><%= user.gender %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <!--Delete a user and all his articles and only the admins can see this link-->
      <% if logged_in? and current_user.admin? %>
        <td><%= link_to "Delete this user", user_path(user), method: :delete,
                        data: {confirm: "Are you sure you want to delete the user and all their articles?"} %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

healthy_food/app/views/users/my_saved.html.erb
<body class="background">

<div class="container-fluid ">
  <div class="row post">
    <div class="col-sm-6 ">


      <% if @saved_recipes.size > 0 %>
        <% @saved_recipes.each do |recipe| %>
          <div class="jumbotron">

            <!--to delete the recipe from the saved-->
            <%= link_to "x", saved_recipe_path(recipe), method: :delete,
                        data: {confirm: "Are you sure?"}, class: "close" %>

            <!--recipe image-->
            <% if recipe.image.attached? %>
              <%= image_tag(recipe.image, class: "img-responsive", width: "200", height: "200") %>
            <% end %>

            <!--recipe name-->
            <%= link_to recipe.name, recipe_path(recipe), class: "post-recipe-title" %>
            <br>

            <br>

            <div class="chip saved-meta-details ">
              <% if recipe.user.profile_photo.attached? %>
                <%= image_tag(recipe.user.profile_photo, :alt => "Person", width: "96", height: "96") %>
              <% else %>
                <%= image_tag("img_avatar.png", class: "img-responsive", width: "160", height: "160") %>
              <% end %>
              <small>Saved from a recipe by
                : <%= link_to recipe.user.username, user_path(recipe.user) if recipe.user %></small>
            </div>

          </div>
        <% end %>
      <% else %>
        <div class="row col-lg-12">
          <p class="lead">
            You don't have any saved recipes yet, please add some!
          </p>
        </div>
      <% end %>

    </div>

    <div class="col-sm-6 ">

      <% if @saved_posts.size > 0 %>
        <% @saved_posts.each do |post| %>
          <div class="jumbotron">
            <!--to delete the post from the saved-->
            <%= link_to "x", saved_post_path(post), method: :delete,
                        data: {confirm: "Are you sure?"}, class: "close" %>


            <!--post image-->
            <% if post.description_image.attached? %>
              <%= image_tag(post.description_image, class: "img-responsive", width: "200", height: "200") %>
            <% end %>

            <!--post name-->
            <%= link_to post.name, post_path(post), class: "post-recipe-title" %>
            <br>

            <div class="chip saved-meta-details">
              <% if post.user.profile_photo.attached? %>
                <%= image_tag(post.user.profile_photo, :alt => "Person", width: "96", height: "96") %>
              <% else %>
                <%= image_tag("img_avatar.png", class: "img-responsive", width: "160", height: "160") %>
              <% end %>
              <small>Saved from a recipe by
                : <%= link_to post.user.username, user_path(post.user) if post.user %></small>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="row col-lg-12">
          <p class="lead">
            You don't have any saved posts yet, please add some!
          </p>
        </div>
      <% end %>

    </div>

  </div>
</div>
</body>

healthy_food/app/views/users/new.html.erb
<body class="container-fluid background">
<%= render 'form', user: @user %>
</body>
<!--%= link_to 'Back', users_path %-->